services:
    _defaults:
        public: true

    Oro\Bundle\DPDBundle\Controller\DPDController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
