parameters:
    oro_dpd.integration.channel.type: 'dpd'
    oro_dpd.integration.transport.type: 'dpd'
    oro_dpd.admin_view.method_template: '@@OroDPD/DPDMethodWithOptions.html.twig'

services:
    oro_dpd.provider.channel:
        class: 'Oro\Bundle\DPDBundle\Provider\ChannelType'
        tags:
            - { name: oro_integration.channel, type: '%oro_dpd.integration.channel.type%' }

    oro_dpd.provider.transport:
          class: 'Oro\Bundle\DPDBundle\Provider\DPDTransport'
          arguments:
              - '@logger'
              - '@oro_security.encoder.default'
          calls:
              - [setRestClientFactory, ['@oro_integration.transport.rest.client_factory']]
          tags:
              - { name: oro_integration.transport, type: '%oro_dpd.integration.transport.type%', channel_type: '%oro_dpd.integration.channel.type%' }

    oro_dpd.provider.package:
        class: 'Oro\Bundle\DPDBundle\Provider\PackageProvider'
        public: false
        arguments:
            - '@oro_shipping.provider.measure_units.conversion'
            - '@oro_locale.helper.localization'

    oro_dpd.provider.rate:
        class: 'Oro\Bundle\DPDBundle\Provider\RateProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@oro_shipping.provider.measure_units.conversion'

    oro_dpd.factory.dpd_request_factory:
        class: 'Oro\Bundle\DPDBundle\Factory\DPDRequestFactory'
        public: false
        arguments:
            - '@oro_order.factory.shipping_context'
            - '@oro_dpd.provider.package'

    oro_dpd.method.identifier_generator.method:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%oro_dpd.integration.channel.type%'

    oro_dpd.method.identifier_generator.type:
        class: 'Oro\Bundle\DPDBundle\Method\Identifier\DPDMethodTypeIdentifierGenerator'
        public: false

    oro_dpd.method.factory.method:
        class: 'Oro\Bundle\DPDBundle\Method\Factory\DPDShippingMethodFactory'
        public: false
        arguments:
            - '@oro_locale.helper.localization'
            - '@oro_dpd.method.identifier_generator.method'
            - '@oro_dpd.method.factory.type'
            - '@oro_dpd.method.factory.dpd_handler'
            - '@oro_integration.provider.integration_icon'

    oro_dpd.method.factory.type:
        class: 'Oro\Bundle\DPDBundle\Method\Factory\DPDShippingMethodTypeFactory'
        public: false
        arguments:
            - '@oro_dpd.method.identifier_generator.type'
            - '@oro_dpd.method.identifier_generator.method'
            - '@oro_dpd.provider.transport'
            - '@oro_dpd.provider.package'
            - '@oro_dpd.provider.rate'

    oro_dpd.method.factory.dpd_handler:
        class: 'Oro\Bundle\DPDBundle\Method\Factory\DPDHandlerFactory'
        public: false
        arguments:
            - '@oro_dpd.method.identifier_generator.type'
            - '@oro_dpd.provider.transport'
            - '@oro_dpd.provider.package'
            - '@oro_dpd.factory.dpd_request_factory'
            - '@oro_dpd.zip_code_rules_cache'
            - '@oro_order.shipping_line_item.converter_basic'

    oro_dpd.shipping_method_provider.dpd:
        class: 'Oro\Bundle\DPDBundle\Method\DPDShippingMethodProvider'
        public: false
        arguments:
            - '%oro_dpd.integration.channel.type%'
            - '@oro_entity.doctrine_helper'
            - '@oro_dpd.method.factory.method'
        tags:
            - { name: oro_shipping_method_provider }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\IntegrationBundle\Entity\Channel', event: postLoad }

    oro_dpd.handler.order_shipping_dpd:
        class: 'Oro\Bundle\DPDBundle\Handler\OrderShippingDPDHandler'
        public: true
        arguments:
            - '@doctrine'
            - '@oro_attachment.file_manager'
            - '@oro_dpd.shipping_method_provider.dpd'
            - '@oro_dpd.transaction.file.name.provider'

    oro_dpd.validator.remove_used_shipping_service:
        class: 'Oro\Bundle\DPDBundle\Validator\Constraints\RemoveUsedShippingServiceValidator'
        arguments:
            - "@oro_dpd.method.factory.method"
            - "@oro_shipping.method_validator.main"
        tags:
            - { name: validator.constraint_validator, alias: oro_dpd_remove_used_shipping_service_validator }

    oro_dpd.validator.rates_csv_file_validator:
        class: 'Oro\Bundle\DPDBundle\Validator\Constraints\RatesCsvFileValidator'
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: validator.constraint_validator, alias: oro_dpd_rates_csv_file_validator }

    oro_dpd.handler.action.invalidate_cache:
        class: 'Oro\Bundle\DPDBundle\Handler\InvalidateCacheActionHandler'
        public: true
        arguments:
            - "@oro_dpd.zip_code_rules_cache"

    oro_dpd.zip_code_rules_cache:
        class: 'Oro\Bundle\DPDBundle\Cache\ZipCodeRulesCache'
        public: false
        arguments:
            - "@oro_dpd.cache.zip_code_rules"

    oro_dpd.cache.zip_code_rules:
        public: false
        parent: oro.cache.abstract
        calls:
            - [setNamespace, ['oro_dpd_zip_code_rules']]

    oro_dpd.repository.rate_repository:
        class: 'Oro\Bundle\DPDBundle\Entity\Repository\RateRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\DPDBundle\Entity\Rate'
