operations:
    oro_dpd_integration_invalidate_cache:
        extends: oro_cache_invalidate
        routes:
            - oro_integration_update
        acl_resource: [UPDATE, entity:Oro\Bundle\IntegrationBundle\Entity\Channel]
        button_options:
            icon: fa-clock-o
        preactions:
            - '@assign_value': [$.invalidateService, 'oro_dpd.handler.action.invalidate_cache']
            - '@assign_constant_value':
                attribute: $.currentChannelType
                value: Oro\Bundle\DPDBundle\Provider\ChannelType::TYPE
            - '@assign_constant_value':
                attribute: $.paramTransportId
                value: Oro\Bundle\DPDBundle\Handler\InvalidateCacheActionHandler::PARAM_TRANSPORT_ID
            - '@call_method':
                object: $.dataStorage
                method: set
                method_parameters:
                    - $.paramTransportId
                    - $.data.transport.id
        preconditions:
            '@equal': [$type, $.currentChannelType]

    oro_dpd_ship_order:
        label: oro.dpd.form.ship_order.label
        routes:
            - oro_order_view
        acl_resource: [UPDATE, entity:Oro\Bundle\OrderBundle\Entity\Order]
        button_options:
            icon: fa-list-alt
        frontend_options:
            template: '@OroDPD/Action/shipOrder.html.twig'
            title: oro.dpd.form.ship_order.title
            options:
                width: 505
                modal: false
                stateEnabled: false
                incrementalPosition: false
                allowMaximize: false
                allowMinimize: false
                maximizedHeightDecreaseBy: minimize-bar
                message: oro.dpd.form.ship_order.message
        attributes:
            shipDate:
                label: oro.dpd.form.ship_order.ship_date.label
                type: object
                options:
                    class: \DateTime
        form_options:
            attribute_fields:
                shipDate:
                    form_type: Oro\Bundle\FormBundle\Form\Type\OroDateType
                    options:
                        disabled: true
            attribute_default_values:
                shipDate: $.shipDate
        form_init:
            - '@call_service_method':
                attribute: $.shipDate
                service: oro_dpd.handler.order_shipping_dpd
                method: getNextPickupDay
                method_parameters: [$.data]
        preactions:
            - '@find_entity':
                class: Oro\Bundle\DPDBundle\Entity\DPDTransaction
                attribute: $.dpdTransaction
                where:
                    order: $.data
        preconditions:
            '@and':
                - '@not_blank': $.data
                - '@shipped_with_dpd': $.data.shippingMethod
                - '@blank': $.dpdTransaction
        actions:
            - '@call_service_method':
                attribute: $.result
                service: oro_dpd.handler.order_shipping_dpd
                method: shipOrder
                method_parameters: [$.data, $.form]
            - '@tree':
                conditions:
                    '@equal': ['$.result[successful]', true]
                actions:
                    - '@call_service_method':
                        service: oro_dpd.order.attachment.factory
                        method: createAttachmentFromDPDTransaction
                        method_parameters: ['$.result[transaction]']
                        attribute: $.orderAttachment
                    - '@call_service_method':
                        service: oro_dpd.handler.order_shipping_dpd
                        method: addTrackingNumbersToOrder
                        method_parameters: [$.data, '$.result[transaction]']
                    - '@flash_message':
                        message: oro.dpd.form.ship_order.flash.success
                        type: 'success'
                    - '@flush_entity': $.orderAttachment
                    - '@refresh_grid': order-shipping-trackings-grid
                    - '@refresh_grid': attachment-grid
            - '@foreach':
                array: $.result[errors]
                value: $.errorMsgTemp
                actions:
                    - '@flash_message':
                        message: $.errorMsgTemp
                        type: 'error'

    oro_dpd_reship_order:
        label: oro.dpd.form.reship_order.label
        routes:
            - oro_order_view
        acl_resource: [UPDATE, entity:Oro\Bundle\OrderBundle\Entity\Order]
        button_options:
            icon: fa-list-alt
        frontend_options:
            template: '@OroDPD/Action/shipOrder.html.twig'
            title: oro.dpd.form.reship_order.title
            options:
                width: 505
                modal: false
                stateEnabled: false
                incrementalPosition: false
                allowMaximize: false
                allowMinimize: false
                maximizedHeightDecreaseBy: minimize-bar
                message: oro.dpd.form.reship_order.message
        attributes:
            shipDate:
                label: oro.dpd.form.reship_order.ship_date.label
                type: object
                options:
                    class: \DateTime
        form_options:
            attribute_fields:
                shipDate:
                    form_type: Oro\Bundle\FormBundle\Form\Type\OroDateType
                    options:
                        disabled: true
            attribute_default_values:
                shipDate: $.shipDate
        form_init:
            - '@call_service_method':
                attribute: $.shipDate
                service: oro_dpd.handler.order_shipping_dpd
                method: getNextPickupDay
                method_parameters: [$.data]
        preactions:
            - '@find_entity':
                class: Oro\Bundle\DPDBundle\Entity\DPDTransaction
                attribute: $.lastDpdTransaction
                where:
                    order: $.data
                order_by:
                    createdAt: DESC
        preconditions:
            '@and':
                - '@not_blank': $.data
                - '@shipped_with_dpd': $.data.shippingMethod
                - '@not_blank': $.lastDpdTransaction
        actions:
            - '@call_service_method':
                attribute: $.result
                service: oro_dpd.handler.order_shipping_dpd
                method: shipOrder
                method_parameters: [$.data, $.form]
            - '@tree':
                conditions:
                    '@equal': ['$.result[successful]', true]
                actions:
                    - '@call_service_method':
                        service: oro_dpd.order.attachment.factory
                        method: createAttachmentFromDPDTransaction
                        method_parameters: ['$.result[transaction]']
                        attribute: $.orderAttachment
                    - '@call_service_method':
                        service: oro_dpd.handler.order_shipping_dpd
                        method: unlinkLabelFromOrder
                        method_parameters: [$.data, $.lastDpdTransaction]
                    - '@call_service_method':
                        service: oro_dpd.handler.order_shipping_dpd
                        method: removeTrackingNumbersFromOrder
                        method_parameters: [$.data, $.lastDpdTransaction]
                    - '@call_service_method':
                        service: oro_dpd.handler.order_shipping_dpd
                        method: addTrackingNumbersToOrder
                        method_parameters: [$.data, '$.result[transaction]']
                    - '@flush_entity': $.orderAttachment
                    - '@flash_message':
                        message: oro.dpd.form.reship_order.flash.success
                        type: 'success'
                    - '@refresh_grid': order-shipping-trackings-grid
                    - '@refresh_grid': attachment-grid
            - '@foreach':
                array: $.result[errors]
                value: $.errorMsgTemp
                actions:
                    - '@flash_message':
                        message: $.errorMsgTemp
                        type: 'error'

    oro_integration_deactivate:
        preactions:
            - '@assign_constant_value':
                attribute: $.currentChannelType
                value: Oro\Bundle\DPDBundle\Provider\ChannelType::TYPE
        preconditions:
            '@and':
                - '@not_equal': [$type, $.currentChannelType]

    oro_integration_delete:
        preactions:
            - '@assign_constant_value':
                attribute: $.currentChannelType
                value: Oro\Bundle\DPDBundle\Provider\ChannelType::TYPE
        preconditions:
            '@and':
                - '@not_equal': [$type, $.currentChannelType]

    oro_dpd_integration_deactivate:
        extends: oro_integration_deactivate
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preactions
            - preconditions
            - frontend_options
        preactions:
            - '@assign_constant_value':
                attribute: $.currentChannelType
                value: Oro\Bundle\DPDBundle\Provider\ChannelType::TYPE
            - '@call_service_method':
                attribute: $.actionAllowed
                service: oro_integration.utils.edit_mode
                method: isSwitchEnableAllowed
                method_parameters: [$.data.editMode]
            - '@call_service_method':
                attribute: $.methodIdentifier
                service: oro_dpd.method.identifier_generator.method
                method: generateIdentifier
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.linkGrid
                service: oro_shipping.helper.filtered_datagrid_route
                method: generate
                method_parameters:  [{'methodConfigs': $.methodIdentifier}]
        preconditions:
            '@and':
                - '@shipping_method_has_enabled_shipping_rules':
                    parameters:
                        method_identifier: $.methodIdentifier
                - '@equal': [$type, $.currentChannelType]
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
        frontend_options:
            confirmation:
                title: oro.shipping.integration.deactivate.title
                okText: oro.shipping.integration.deactivate.button.okText
                message: oro.shipping.integration.deactivate.message
                message_parameters:
                    linkGrid: $.linkGrid
                component: oroui/js/standart-confirmation

    oro_dpd_integration_deactivate_without_rules:
        extends: oro_dpd_integration_deactivate
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - frontend_options
        preconditions:
            '@and':
                - '@not':
                    - '@shipping_method_has_enabled_shipping_rules':
                        parameters:
                            method_identifier: $.methodIdentifier
                - '@equal': [$type, $.currentChannelType]
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
        frontend_options: ~

    oro_dpd_integration_delete:
        extends: oro_integration_delete
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preactions
            - preconditions
            - frontend_options
        preactions:
            - '@assign_constant_value':
                attribute: $.currentChannelType
                value: Oro\Bundle\DPDBundle\Provider\ChannelType::TYPE
            - '@call_service_method':
                service: oro_integration.utils.edit_mode
                method: isEditAllowed
                method_parameters: [$.data.editMode]
                attribute: $.actionAllowed
            - '@call_service_method':
                attribute: $.methodIdentifier
                service: oro_dpd.method.identifier_generator.method
                method: generateIdentifier
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.linkGrid
                service: oro_shipping.helper.filtered_datagrid_route
                method: generate
                method_parameters:  [{'methodConfigs': $.methodIdentifier}]
        preconditions:
            '@and':
                - '@shipping_method_has_shipping_rules':
                    parameters:
                        method_identifier: $.methodIdentifier
                - '@equal': [$type, $.currentChannelType]
                - '@equal': [$.actionAllowed, true]
        frontend_options:
            confirmation:
                title: oro.shipping.integration.delete.title
                okText: oro.shipping.integration.delete.button.okText
                message: oro.shipping.integration.delete.message
                message_parameters:
                    linkGrid: $.linkGrid
                component: oroui/js/standart-confirmation

    oro_dpd_integration_delete_without_rules:
        extends: oro_dpd_integration_delete
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - frontend_options
        preconditions:
            '@and':
                - '@not':
                    - '@shipping_method_has_shipping_rules':
                        parameters:
                            method_identifier: $.methodIdentifier
                - '@equal': [$type, $.currentChannelType]
                - '@equal': [$.actionAllowed, true]
        frontend_options:
            title: oro.action.delete_entity
            confirmation:
                title: oro.action.delete_entity
                message: oro.action.delete_confirm
                message_parameters:
                    entityLabel: $name
